# SPDX-FileCopyrightText: 2024 Luca Bassi
# SPDX-License-Identifier: GPL-3.0-or-later
name: Build package
on: [push, pull_request]
jobs:
  build-ubuntu:
    strategy:
      matrix:
        runners: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake gcc-riscv64-unknown-elf libelf-dev libsigc++-2.0-dev libboost-dev libboost-program-options-dev qt6-base-dev libglx-dev libgl1-mesa-dev
      - name: Create .deb
        run: |
          mkdir build
          cd build
          cmake ..
          cpack -G DEB
      - uses: actions/upload-artifact@v4
        with:
          name: build-ubuntu-${{ runner.arch }}
          path: build/*.deb
  build-debian:
    strategy:
      matrix:
        runners: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runners }}
    container: 'debian:latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y g++ cmake gcc-riscv64-unknown-elf libelf-dev libsigc++-2.0-dev libboost-dev libboost-program-options-dev qt6-base-dev libglx-dev libgl1-mesa-dev
      - name: Create .deb
        run: |
          mkdir build
          cd build
          cmake ..
          cpack -G DEB
      - uses: actions/upload-artifact@v4
        with:
          name: build-debian-${{ runner.arch }}
          path: build/*.deb
  build-fedora:
    strategy:
      matrix:
        runners: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runners }}
    container: 'fedora:latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf upgrade -y
          dnf install -y gcc-c++ cmake gcc-riscv64-linux-gnu elfutils-libelf-devel libsigc++20-devel boost-devel qt6-qtbase-devel rpm-build
      - name: Create .rpm
        run: |
          mkdir build
          cd build
          cmake -DRISCV_TOOL_PREFIX="riscv64-linux-gnu-" ..
          cpack -G RPM
      - uses: actions/upload-artifact@v4
        with:
          name: build-fedora-${{ runner.arch }}
          path: build/*.rpm
  publish:
    needs: [build-ubuntu, build-debian, build-fedora]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Create release
        run: |
          gh release delete latest --cleanup-tag --yes || true
          gh release create latest --title "Latest release" --notes "Only Debian stable (amd64) is officially supported" build-*/*
